### ISSUE TITLE
Create database

### ISSUE THREAD

**Issue by 21Chaano** [Academic-Panic/academic-panic-application#17]
Create the database to be used for Academic Panic

Database entries:
+ user
    + username
    + password
+ \@
    + courses
        + class
        + semester
        + year
        + instructor
        + enrollment type
            + student
            + TA
            + grader
        + interest type
    + friends
        + friends list
        + friend requests

**Comment by elwais** [comment]
See #20 for how the username was added.

**Comment by elwais** [comment]
See 3c384904229931599f4989510cc3dc1fa341d22c for some stubs of the Prisma schema.

**Comment by elwais** [comment]
After a brief discussion with @21Chaano and @Zeniscribbles, courses will take on a one-to-many mapping to different students. *(This is of course subject to change.)*

Due to each model requiring some sort of attribute that distinguishes different instances from each other (like an ID number for example), courses will now take on a one-to-many mapping to different students. The alternative was to have each student contain their own records of courses, but that could cause needless duplication, and courses are inherently centralized. (Many students take a single course.) Work will be needed to add validation, but this decision should add robustness to course addition, lend itself well to summary statistics for the landing page, and make certain features (invalidating certain course additions) easier to implement.

**Comment by Zeniscribbles** [comment]
Hey Elwais,

    I asked chatGPT and it mentioned a many to many relationship. I also
asked for resources for us to read up. Here is the convo.
https://chatgpt.com/share/674529d3-e46c-800c-9414-425ac0206742

Zeni

**Comment by elwais** [comment]
Hi Zeni,

I had a brief look at ChatGPT's implementation, and it does look promising! I'll see if I can learn from or mimic its implemention to fit out use case. Thanks for the idea!

Elwais

**Comment by elwais** [comment]
ChatGPT helpfully linked to the [many-to-many](https://www.prisma.io/docs/orm/prisma-schema/data-model/relations/many-to-many-relations#implicit-many-to-many-relations) Prisma documentation, and it looks like many-to-many is the only way to proceed here. (If I'm understanding it correctly, there is a table for each model, and our structure would have a table of students and a table of courses. The only way to link multiple students to multiple different courses is to use a many-to-many relation.)

There's also details on how to interact with Prisma in the ChatGPT log, which would come in handy for the frontend work by @21Chaano.

**Comment by elwais** [comment]
See 397831993d987d0d4052965df269bd25474ac80b for how compound uniqueness searching is done when calling `where` in a Prisma CRUD operation.

NOTE: This operation may become useful if courses are ID'd by a combination of their attributes instead of an ID number. It makes more sense to search for semester, year, instructor, title, and section rather than using that as an intermediate to then look up an ID number.

**Comment by elwais** [comment]
Save for enrollment type, friends, and interest type, the database and operations that interface with it have been implemented using "Add Stuff" and "Edit Stuff" as a template with f1be581f3bba03fb56d46cb896caa3c401d442f4. Continued work will be done in later issues - possibly starting with #18.
