### ISSUE TITLE
Typescript language server error in AddStuffForm.tsx

### ISSUE THREAD

**Issue by 21Chaano** [Academic-Panic/academic-panic-application#27]

**Comment by elwais** [comment]
The typescript language server error was caused due to a type mismatch between the enums specified in the Prisma schema and the native Typescript string. Frontend validation will be used instead of the backend (as the "hacks" required in the backend make for slightly unpleasant code). This has been resolved with a79f17e73499e1e81daccca4c11e51feaf331983.
